# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./main.go"
  bin = "./tmp/main"
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  include_ext = ["go", "tpl", "sql", "tmpl", "html"]
  delay = 1000 # ms
  stop_on_error = true

[log]
  time = true
  verbose = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
