// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID          pgtype.UUID        `json:"id"`
	DateTime    pgtype.Timestamptz `json:"date_time"`
	Type        string             `json:"type"`
	ReceptionID pgtype.UUID        `json:"reception_id"`
	Sequence    int64              `json:"sequence"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Pvz struct {
	ID               pgtype.UUID        `json:"id"`
	RegistrationDate pgtype.Timestamptz `json:"registration_date"`
	City             string             `json:"city"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Reception struct {
	ID        pgtype.UUID        `json:"id"`
	DateTime  pgtype.Timestamptz `json:"date_time"`
	PvzID     pgtype.UUID        `json:"pvz_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
